# Generated by Django 4.0.3 on 2022-03-05 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Group3Capstone', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
