# Generated by Django 3.2.3 on 2022-04-28 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Group3Capstone', '0004_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Event_Description',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='Event_Name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='Group_Description',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='Group_Name',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='group',
            name='Joined_Users',
            field=models.ManyToManyField(related_name='Joining_User', to='Group3Capstone.User'),
        ),
        migrations.AddField(
            model_name='group',
            name='SpotsAvailable',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='Location',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='Creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Group_Creator', to='Group3Capstone.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='User_Password',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='User_Phone',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.CreateModel(
            name='GroupReservation',
            fields=[
                ('GroupReservation_Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Group3Capstone.group')),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Group3Capstone.user')),
            ],
        ),
        migrations.CreateModel(
            name='GroupPost',
            fields=[
                ('GroupPostID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=40, null=True)),
                ('BodyText', models.CharField(max_length=256, null=True)),
                ('Date', models.DateTimeField(null=True)),
                ('Creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Group3Capstone.user')),
                ('Group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Group3Capstone.group')),
            ],
        ),
    ]
